language: php

addons:
  postgresql: "13.0"

services:
  - mysql
  - postgresql
  - docker

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 8.0
  - 8.1

env:
  global:
    - MOODLE_BRANCH=MOODLE_403_STABLE
  matrix:
    - DB=pgsql
    - DB=mysqli

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:1} -gt 7 ]]; then pecl install xmlrpc-beta; fi
  - echo 'max_input_vars=8000' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci add-plugin --branch MOODLE_403_STABLE YU-MITC/moodle-local_yukaltura
  - moodle-plugin-ci add-plugin --branch MOODLE_403_STABLE YU-MITC/moodle-local_yumymedia
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt --tasks amd
  - moodle-plugin-ci grunt --tasks gherkinlint
  - moodle-plugin-ci phpdoc
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
